[tool]
[tool.poetry]
name = "gbtarchive_orm"
version = "0.0.0"
authors = ["Thomas Chamberlin <tchamber@nrao.edu>"]
description = ""

[tool.poetry.dependencies]
python = "^3.6"
django = ">=2.2.3"
django-extensions = "^2.2.1"
mysqlclient = "1.4.6"

[tool.poetry.dev-dependencies]
ipython = "^7.7"
