# Generated by Django 2.2.3 on 2019-07-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('coordinateid', models.AutoField(db_column='coordinateID', primary_key=True, serialize=False)),
                ('ra', models.FloatField(db_column='RA')),
                ('dec', models.FloatField(db_column='DEC')),
                ('coordinatesystem', models.CharField(db_column='coordinateSystem', max_length=64)),
                ('equinox', models.IntegerField()),
                ('radesys', models.IntegerField()),
                ('planetary', models.IntegerField()),
                ('obsaz', models.FloatField()),
                ('obsel', models.FloatField()),
                ('raj2000', models.FloatField(db_column='RAJ2000')),
                ('decj2000', models.FloatField(db_column='DECJ2000')),
            ],
            options={
                'db_table': 'coordinates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('errorid', models.AutoField(db_column='errorID', primary_key=True, serialize=False)),
                ('errormsg', models.CharField(db_column='errorMsg', max_length=64)),
                ('severity', models.IntegerField()),
            ],
            options={
                'db_table': 'error',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('fileid', models.AutoField(db_column='fileID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('date', models.DateTimeField()),
                ('size', models.IntegerField()),
            ],
            options={
                'db_table': 'file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('historyid', models.AutoField(db_column='historyID', primary_key=True, serialize=False)),
                ('archivaldate', models.DateField(db_column='archivalDate')),
                ('aatfilename', models.CharField(db_column='aatFilename', max_length=256)),
                ('version', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name_plural': 'Histories',
                'db_table': 'history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('observerid', models.AutoField(db_column='observerID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'Observer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObsParameter',
            fields=[
                ('obsparameterid', models.AutoField(db_column='obsParameterID', primary_key=True, serialize=False)),
                ('backend', models.CharField(max_length=64)),
                ('receiver', models.CharField(max_length=1024)),
                ('nchan', models.CharField(max_length=1024)),
                ('bandwidth', models.CharField(max_length=1024)),
                ('velocity', models.FloatField()),
                ('velocitydef', models.CharField(db_column='velocityDef', max_length=64)),
                ('restfreq', models.CharField(max_length=1024)),
                ('poln', models.CharField(max_length=64)),
                ('poln_num', models.CharField(max_length=64)),
                ('mode', models.CharField(max_length=64)),
                ('recband', models.CharField(db_column='recBand', max_length=12)),
            ],
            options={
                'verbose_name': 'Obs. Parameter',
                'db_table': 'obsParameter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObsProcedure',
            fields=[
                ('obsprocedureid', models.AutoField(db_column='obsProcedureID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('obstype', models.CharField(db_column='obsType', max_length=64)),
                ('procscan', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Obs. Procedure',
                'db_table': 'obsProcedure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectid', models.AutoField(db_column='projectID', primary_key=True, serialize=False)),
                ('propname', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('scanid', models.AutoField(db_column='scanID', primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('object', models.CharField(max_length=64)),
                ('obsidentifier', models.CharField(db_column='obsIdentifier', max_length=64)),
                ('dateobserved', models.DateTimeField(db_column='dateObserved')),
                ('integrationtime', models.FloatField(db_column='integrationTime')),
                ('scanlength', models.IntegerField()),
                ('archived', models.IntegerField()),
            ],
            options={
                'db_table': 'scan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionid', models.AutoField(db_column='sessionID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('gofitsversion', models.CharField(db_column='GOFitsVersion', max_length=64)),
                ('msgflag', models.CharField(db_column='MSGFLAG', max_length=1024)),
                ('msglevel', models.CharField(db_column='MSGLEVEL', max_length=4)),
            ],
            options={
                'db_table': 'session',
                'managed': False,
            },
        ),
    ]
